spring:
  application:
    name: DoAnTotNghiep

  datasource:
    url: jdbc:mysql://localhost:3306/doantotnghiep?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: Minh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Hoặc "validate" nếu bạn không muốn thay đổi cấu trúc bảng trong quá trình phát triển
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true  # Hiển thị câu lệnh SQL khi debug

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration  # Chỉ định thư mục chứa file migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: phananhminh24@gmail.com
    password: oqij icjr zawz hkcl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8088

logging:
  level:
    root: INFO
    org.hibernate: ERROR

app:
  jwtSecret: bXlTZXJldEtleUxvbmclw6qI8TKZ9WXzH+OaD4jRge7xVtkA7tSy75cFDi5Jw==
  jwtExpirationMs: 604800000
